apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ziad-tarek/test-repo.git
    targetRevision: HEAD
    path: kubernetes/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: skyebank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
