apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skyebank-ingress
  namespace: skyebank
  annotations:
    # # Instruct Prometheus to scrape this endpoint if metrics are exposed
    # prometheus.io/scrape: "true"
    # prometheus.io/port: "80"
    # # Annotation for NGINX ingress controller to rewrite URLs if needed
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: skyebank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skyebank-service
                port:
                  number: 8080
